name: "Flatpak build"

on:
  workflow_call:

env:
  GODOT_VERSION: 4.6.3

jobs:
  flatpak-build:
    name: Flatpak build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Setup
        run: |
          ## Create pck
          wget https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip -O /tmp/godot.zip
          pushd /tmp
          unzip godot.zip
          popd
          /tmp/Godot*.x86_64 --headless --import || true
          /tmp/Godot*.x86_64 --headless --export-pack "Linux" dreamdeck.pck

          ## Install poetry
          PATH="$PATH:$HOME/.local/bin"
          python -m pip install pipx
          pipx install poetry

          ## Cargo-source jsons setup
          git clone https://github.com/flatpak/flatpak-builder-tools.git /tmp/flatpak-builder-tools
          pushd /tmp/flatpak-builder-tools/cargo
          poetry install
          poetry env activate
          poetry run python flatpak-cargo-generator.py \
            -o $GITHUB_WORKSPACE/dist/cargo-source1.json $GITHUB_WORKSPACE/plugins/ssh/rust/Cargo.lock
          poetry run python flatpak-cargo-generator.py \
            -o $GITHUB_WORKSPACE/dist/cargo-source2.json $GITHUB_WORKSPACE/plugins/touch/rust/Cargo.lock
          popd
      - name: Build flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: dreamdeck.flatpak
          manifest-path: dist/dev.jcronenberg.DreamDeck.yml
          # Cargo locks as cache-keys because they contain the only relevant files that take a long time
          cache-key: flatpak-builder-${{ hashFiles('plugins/touch/rust/Cargo.lock', 'plugins/ssh/rust/Cargo.lock') }}
          upload-artifact: false
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dreamdeck-flatpak
          path: ./dreamdeck.flatpak
