name: OBS package

on:
  workflow_call:

jobs:
  update-obs-package:
    # only publish if push to main repo and branch
    if: github.repository == 'jcronenberg/DreamDeck' && github.event_name == 'push' && github.ref == 'refs/heads/prototyping'

    name: "Update dev OBS package"
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/home/jcronenberg/github-ci/containers/opensuse/obs-build:latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Configure osc
        run: .github/workflows/configure_osc.sh
        env:
          OBS_USER: ${{ secrets.OBS_USER }}
          OBS_PW: ${{ secrets.OBS_PW }}
      - name: Checkout package
        run: osc checkout home:jcronenberg:dreamdeck/dreamdeck -o dreamdeck-package
      - name: Remove current obscpio
        run: rm -f *.obscpio
        working-directory: ./dreamdeck-package
      - name: Run osc service manualrun
        run: osc service manualrun
        working-directory: ./dreamdeck-package
      - name: Update current files in osc
        run: osc ar
        working-directory: ./dreamdeck-package
      - name: Commit to OBS
        run: osc commit -m "$GITHUB_SHA"
        working-directory: ./dreamdeck-package
      - name: Watch OBS result
        shell: bash {0}
        run: |
          timeout 900 osc results -w -F
          r=$?
          if [ $r -eq 124 ]; then
            echo "::warning ::OBS build timed out"
            exit 0
          else
            exit $r
          fi
        working-directory: ./dreamdeck-package