name: "Static checks"

on:
  workflow_call

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_touch_checks:
    name: Rust checks for touch plugin
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Git Checkout
      uses: actions/checkout@v5
    - name: Install toolchain
      run: rustup toolchain install stable
    - uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          plugins/touch/rust/target/
        key: static-touch-cargo-${{ hashFiles('plugins/touch/rust/Cargo.lock') }}
    - name: Lint tests
      run: cargo fmt --all -- --check
      working-directory: ./plugins/touch/rust
    - name: Cargo clippy
      run: cargo clippy -- --no-deps -D warnings
      working-directory: ./plugins/touch/rust

  rust_ssh_checks:
    name: Rust checks for ssh plugin
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Git Checkout
      uses: actions/checkout@v5
    - name: Install toolchain
      run: rustup toolchain install stable
    - uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          plugins/ssh/rust/target/
        key: static-ssh-cargo-${{ hashFiles('plugins/ssh/rust/Cargo.lock') }}
    - name: Lint tests
      run: cargo fmt --all -- --check
      working-directory: ./plugins/ssh/rust
    - name: Cargo clippy
      run: cargo clippy -- --no-deps -D warnings
      working-directory: ./plugins/ssh/rust

  gd_checks:
    name: GDScript checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: Scony/godot-gdscript-toolkit@master
      - name: Formatting checks
        run: gdformat --diff .
      - name: Linting checks
        run: gdlint .

  spell_checks:
    name: Spell checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Spell checks via codespell
        uses: codespell-project/actions-codespell@v2
        with:
          skip: ./addons,./addon_submodules,godottpd,Cargo.lock
          ignore_words_list: couldn